### ISSUE TITLE
作成画面の決定

### ISSUE THREAD

**Issue by allface017** [morijyobi/python_flask_web_final_exercise_2023-allface017#1]
- ログイン
- 新規登録
- 新規登録確認
- 新規登録結果
- 利用者トップページ
- 管理者トップページ
- 就職活動報告書提出
- 就職活動報告書再提出
- 就職活動報告書　確認
- 就職活動報告書　結果

**Comment by allface017** [comment]
-  管理者画面　就職活動報告書　登録・返却
-  管理者画面　就職活動報告書登録結果
-  管理者画面　就職活動報告書　返却結果
-  就職活動報告書　一覧表示
-  就職活動報告書　検索結果表示
-  就職活動報告書　詳細表示
-  管理者画面　就職活動報告書　一覧表示
-  管理者画面　就職活動報告書　検索結果表示

**Comment by allface017** [comment]
-  管理者画面　就職活動報告書編集
-  管理者画面　就職活動報告書編集結果
- 管理者画面　就職活動報告書削除
-  管理者画面　就職活動報告書削除結果

**Comment by allface017** [comment]
# 作成画面を決定

**Comment by allface017** [comment]
作成画面の追加

**Comment by allface017** [comment]
- [ ] ログイン
- [ ] 新規登録
- [ ] 新規登録確認
- [ ] 新規登録結果
- [ ] 利用者トップページ
- [ ] 管理者トップページ
- [ ] 就職活動報告書提出
- [ ] 就職活動報告書再提出
- [ ] 就職活動報告書　確認
- [ ] 就職活動報告書　結果
- [ ] 管理者画面　就職活動報告書　登録・返却
- [ ] 管理者画面　就職活動報告書登録結果
- [ ] 管理者画面　就職活動報告書　返却結果
- [ ] 就職活動報告書　一覧表示
- [ ] 就職活動報告書　検索結果表示
- [ ] 就職活動報告書　詳細表示
- [ ] 管理者画面　就職活動報告書　一覧表示
- [ ] 管理者画面　就職活動報告書　検索結果表示
- [ ] 管理者画面　求人票　登録
- [ ] 管理者画面　求人票登録結果
- [ ] 求人票　一覧表示
- [ ] 求人票　検索結果表示
- [ ] 求人票　詳細表示
- [ ] 管理者画面　求人票　一覧表示
- [ ] 管理者画面　求人票　検索結果表示
- [ ] 管理者画面　求人票　詳細表示
- [ ] 管理者画面　求人票編集
- [ ] 管理者画面　求人票編集結果
- [ ] 管理者画面　求人票削除
- [ ] 管理者画面　求人票削除結果
- [ ] 管理者画面　その他就職関連情報登録
- [ ] 管理者画面　その他就職関連情報登録結果
- [ ] その他就職関連情報　一覧表示
- [ ] その他就職関連情報　検索結果表示
- [ ] その他就職関連情報　詳細表示
- [ ] 管理者画面　その他就職関連情報一覧表示
- [ ] 管理者画面　その他就職関連情報検索結果表示
- [ ] 管理者画面　その他就職関連情報詳細表示
- [ ] 管理者画面　その他就職関連情報編集
- [ ] 管理者画面　その他就職関連情報編集結果
- [ ] 管理者画面　その他就職関連情報削除
- [ ] 管理者画面　その他就職関連情報削除結果

**Comment by hosokawa3217** [comment]
### todo 
@allface017 
XD作成した各画面のプロトタイプをこのissueに貼ってください。

**Comment by allface017** [comment]
### TOP画面
- [ ] ログイン
![1 ログイン](https://github.com/morijyobi/python_flask_web_final_exercise_2023-allface017/assets/113155656/d6633ba5-1a71-4782-8fce-cc49a1bbbfcc)
![2 利用者新規登録](https://github.com/morijyobi/python_flask_web_final_exercise_2023-allface017/assets/113155656/f56ab005-d435-470d-9fa1-3e0814d70e9d)
![3 利用者新規登録　確認](https://github.com/morijyobi/python_flask_web_final_exercise_2023-allface017/assets/113155656/c0a962e2-37d4-4fa0-ade1-e262057c16a2)
![4 利用者新規登録　結果](https://github.com/morijyobi/python_flask_web_final_exercise_2023-allface017/assets/113155656/4ed2616a-fb8f-45bf-9228-77315cc63298)
![5 利用者トップメニュー](https://github.com/morijyobi/python_flask_web_final_exercise_2023-allface017/assets/113155656/2c889ff7-5d9e-44fd-aff3-ee914ae9db41)
![6 管理者トップメニュー](https://github.com/morijyobi/python_flask_web_final_exercise_2023-allface017/assets/113155656/af1e0144-aef3-4f4a-a533-6e39f7b07739)
![7 就職活動報告書　提出](https://github.com/morijyobi/python_flask_web_final_exercise_2023-allface017/assets/113155656/12718201-cf37-4d51-b3bf-88c04d83dfd9)
![8 就職活動報告書提出　確認](https://github.com/morijyobi/python_flask_web_final_exercise_2023-allface017/assets/113155656/d5392f97-c6ff-4327-b103-f068e856f598)
![9 就職活動報告書提出　結果](https://github.com/morijyobi/python_flask_web_final_exercise_2023-allface017/assets/113155656/8d4798bc-d469-4378-a138-aaa8cad36c76)
![11 就職活動報告書再提出　確認](https://github.com/morijyobi/python_flask_web_final_exercise_2023-allface017/assets/113155656/de900195-4078-44bf-ac4a-e36de972b3ce)
![Uploading 12 就職活動報告書再提出　結果.png…]()
![13 管理者画面　就職活動報告書　登録・返却](https://github.com/morijyobi/python_flask_web_final_exercise_2023-allface017/assets/113155656/0164052a-3e19-4302-8bc6-279ba8376890)
![14 管理者画面　就職活動報告書登録結果](https://github.com/morijyobi/python_flask_web_final_exercise_2023-allface017/assets/113155656/eaf8a7d6-24ad-43fe-ade2-9a1bec076258)
![15 管理者画面　就職活動報告書　返却結果](https://github.com/morijyobi/python_flask_web_final_exercise_2023-allface017/assets/113155656/d1c5b658-567d-4d13-a81c-3f23f35b238a)
![16 就職活動報告書　一覧表示](https://github.com/morijyobi/python_flask_web_final_exercise_2023-allface017/assets/113155656/a40cf3e7-741f-4f26-bedd-54f77b0fe0d6)
![17 就職活動報告書　検索結果表示](https://github.com/morijyobi/python_flask_web_final_exercise_2023-allface017/assets/113155656/cb98156c-3ddd-4712-afcb-9b5ff74168c2)
![18 就職活動報告書　詳細表示](https://github.com/morijyobi/python_flask_web_final_exercise_2023-allface017/assets/113155656/52ac7ce6-e819-4669-910e-07f0ec8383c2)
![19 管理者画面　就職活動報告書　一覧表示](https://github.com/morijyobi/python_flask_web_final_exercise_2023-allface017/assets/113155656/0990eff5-1194-4b8c-aafb-2286e1bde25a)
![20 管理者画面　就職活動報告書　検索結果表示](https://github.com/morijyobi/python_flask_web_final_exercise_2023-allface017/assets/113155656/d3ee35ce-5981-4774-b647-87f9ab07ab7b)
![21 管理者画面　就職活動報告書　詳細表示](https://github.com/morijyobi/python_flask_web_final_exercise_2023-allface017/assets/113155656/ce720c57-15f2-40aa-b7e1-b0ac4f8fdef2)
![22 管理者画面　就職活動報告書編集](https://github.com/morijyobi/python_flask_web_final_exercise_2023-allface017/assets/113155656/37babbd2-1327-4068-aeb6-0e353c047498)
![23 管理者画面　就職活動報告書編集結果](https://github.com/morijyobi/python_flask_web_final_exercise_2023-allface017/assets/113155656/7dd3d59b-b1fa-4425-af09-7366ab580543)
![24 管理者画面　就職活動報告書削除 – 1](https://github.com/morijyobi/python_flask_web_final_exercise_2023-allface017/assets/113155656/91cada46-a786-4492-bfc3-eeb505f54dc6)
![25 管理者画面　就職活動報告書削除結果](https://github.com/morijyobi/python_flask_web_final_exercise_2023-allface017/assets/113155656/38bc4c5e-bb34-4422-9aac-be7a153f8c69)
![26 管理者画面　求人票　登録](https://github.com/morijyobi/python_flask_web_final_exercise_2023-allface017/assets/113155656/d95a6a8a-e236-46a3-a6f1-514aab911783)
![27 管理者画面　求人票登録結果](https://github.com/morijyobi/python_flaskweb_final_exercise_2023-allface017/assets/113155656/bae27e91-730e-4111-b488-042
![29求人票　検索結果表示](https://github.com/morijyobi/python_flask_web_final_exercise_2023-allface017/assets/113155656/e5a442e4-2ba8-4ae3-b1b0-2d6d3ceea372)
d2c0af1b8)
![28 求人票　一覧表示](https://github.com/morijyobi/python_flask_web_final_exercise_2023-allface017/assets/113155656/2c44ca4b-85ab-44fd-813b-c4944d9a5837)
![29求人票　検索結果表示](https://github.com/morijyobi/python_flask_web_final_exercise_2023-allface017/assets/113155656/edef3c60-1c2f-422f-b780-8ea68368d232)
![30 求人票　詳細表示](https://github.com/morijyobi/python_flask_web_final_exercise_2023-allface017/assets/113155656/358dbbfa-fcc3-4ca3-8815-9e3daf5a0b5b)
![31 管理者画面　求人票　一覧表示](https://github.com/morijyobi/python_flask_web_final_exercise_2023-allface017/assets/113155656/6b
![32 管理者画面　求人票　検索結果表示](https://github.com/morijyobi/python_flask_web_final_exercise_2023-allface017/assets/113155656/ce77f41d-9d1a-42de-84db-61da645bb821)
c4cab5-3bd7-4b1f-b6d5-b7b7991f5bd4)
![33 管理者画面　求人票　詳細表示](https://github.com/morijyobi/python_flask_web_final_exercise_2023-allface017/assets/113155656/4ec46751-db28-448d-9be2-9e32673324ef)
![34 管理者画面　求人票編集](https://github.com/morijyobi/python_flask_web_final_exercise_2023-allface017/assets/113155656/07bd7019-1f86-496a-8dab-20748c11226c)
![35 管理者画面　求人票編集結果](https://github.com/morijyobi/python_flask_web_final_exercise_2023-allface017/assets/113155656/7d4c1f93-6f64-4382-9479-0e1c4df01d4b)
![36 管理者画面　求人票削除](https://github.com/morijyobi/python_flask_web_final_exercise_2023-allface017/assets/113155656/067b7516-a2b2-4d58-889a-961a595a0bf9)
![37 管理者画面　求人票削除結果](https://github.com/morijyobi/python_flask_web_final_exercise_2023-allface017/assets/113155656/65ef1262-9c98-4a3a-a37c-50cd847852e8)
![38 管理者画面　その他就職関連情報　登録](https://github.com/morijyobi/python_flask_web_final_exercise_2023-allface017/assets/113155656/7c5ba46b-b966-4334-a626-ba75a4b6c323)
![39 管理者画面　その他就職関連情報登録結果](https://github.com/morijyobi/python_flask_web_final_exercise_2023-allface017/assets/113155656/c1537d52-23ca-48da-af81-d17f1289f8be)
![40 その他就職関連情報　一覧表示](https://github.com/morijyobi/python_flask_web_final_exercise_2023-allface017/assets/113155656/24857bba-a5fc-4bba-a15f-a7b9ca01c8b4)
![41 その他就職関連情報　検索結果表示](https://github.com/morijyobi/python_flask_web_final_exercise_2023-allface017/assets/113155656/7336663f-7b18-4560-9aaa-b50b6c991850)
![42 その他就職関連情報　詳細表示](https://github.com/morijyobi/python_flask_web_final_exercise_2023-allface017/assets/113155656/fe6885bc-7fd3-4f78-8152-c226fb6e70f9)
![43 管理者画面　その他就職関連情報　一覧表示](https://github.com/morijyobi/python_flask_web_final_exercise_2023-allface017/assets/113155656/45dd05c4-cc8
![44 管理者画面　その他就職関連情報　検索結果表示](https://github.com/morijyobi/python_flask_web_final_exercise_2023-allface017/assets/113155656/cdbfe1e5-9cd3-464f-a9f9-db26c37472ee)
7-4c17-8159-1c8c3a674c35)
![45 管理者画面　その他就職関連情報　詳細表示](https://github.com/morijyobi/python_flask_web_final_exerci
![46  管理者画面　その他就職関連情報編集](https://github.com/morijyobi/python_flask_web_final_exercise_2023-allface017/assets/113155656/f8b3a3f8-2702-4f6f-bfb6-d37ffc1b8cc6)
se_2023-allface017/assets/113155656/459535c6-b77b-443a-b75d-ea60d9abe919)
![47 管理者画面　その他就職関連情報編集結果](https://github.com/morijyobi/python_flask_web_final_exercise_2023-allface017/assets/113155656/2293d4a9-3b9b-4e3e-b47f-6a7d9659a968)
![48 管理者画面　その他就職関連情報削除](https://github.com/morijyobi/python_flask_web_final_exercise_2023-allface017/assets/113155656/84c4bb7b-e007-446d-870c-de4360818e86)
![49 管理者画面　その他就職関連情報削除結果](https://github.com/morijyobi/python_flask_web_final_exercise_2023-allface017/assets/113155656/e788d497-af92-45a2-8b91-f268f04463fd)

**Comment by hosokawa3217** [comment]
確認しました。
作成する画面が多いので、コーディングする際に抜け漏れがないように注意して臨んでください。
issueにチェックリストを作るとよいでしょう。
